### ISSUE TITLE
Settings screen does not show app version number (`0.1.0`)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#159]
### Bug summary

Settings screen does not show app version number (`0.1.0`).

### Bug details

On the "Settings" page, I expected the version number (`0.1.0`) to be visible. In reality, it was not visible.

Here's a screenshot of the "Settings" page, in the Android simulator:

![image](https://github.com/user-attachments/assets/11b3fb07-25a4-4b86-b38a-c2700b97604a)

A teammate confirmed that this was the case on a physical Android device also (although he was using an older version of the app in that case).

### Steps to reproduce

1. Open Android app
2. Go to Settings tab
3. See absence of version number

### App version

0.1.0

### Device type

Android

### Operating system version

TBD

**Comment by eecavanna** [comment]
CC: @yxu-lanl , @pkalita-lbl

**Comment by eecavanna** [comment]
It's affecting iOS also.

![image](https://github.com/user-attachments/assets/bf1fb135-f74d-4948-8752-96a4a48ad15b)

**Comment by eecavanna** [comment]
The version number _is_ visible on the PWA version of the app:

![image](https://github.com/user-attachments/assets/da11d46a-a443-4d82-9eb4-77a79a4791fb)

**Comment by eecavanna** [comment]
On version `0.0.1 (3)` on my physical iPhone, the issue does not occur.

![image](https://github.com/user-attachments/assets/89380087-66d7-43c9-8ef0-621e982a014c)

The issue seems to me to be specific to version `0.1.0 (2)`.

What changed? One thing is that `0.1.0 (2)` was built on someone else's computer, whereas `0.0.1 (3)` was built on my computer. I wonder whether I have something in my environment that made the version number work. 🤔

**Comment by eecavanna** [comment]
Maybe it has to do with the steps used to build the app. When I would built it, I would (happen to) run `npm run sim.ios` at some point. I don't think that was done today on the other person's laptop, but I don't remember for sure.

**Comment by eecavanna** [comment]
I created an Android build on my computer just now by following the steps in the release documentation (in this repo), and the issue was present.

<img width="462" alt="image" src="https://github.com/user-attachments/assets/f370101a-4709-464a-80d2-7a5ad8c617f4">

Then, I ran `$ npm run sim.android`, and the issue was absent (i.e. the version number did appear).

<img width="449" alt="image" src="https://github.com/user-attachments/assets/3e84452d-e654-4cd1-9f81-3c45e26cf78a">

CC: @pkalita-lbl

**Comment by eecavanna** [comment]
Similarly, if I go to Xcode and click `Product` > `Run`, I see the issue is present (i.e. the version number is absent).

![image](https://github.com/user-attachments/assets/dd404211-9fed-44e0-bc72-79ec2d7fca1d)

However, if I run `$ npm run sim.ios`, I see the issue is absent (i.e. the version number is present).

![image](https://github.com/user-attachments/assets/235263df-5786-486c-b5a2-ed2e43133c6a)

CC: @pkalita-lbl

**Comment by pkalita-lbl** [comment]
Interesting! Obviously warrants further investigation to understand what `npm run sim.*` is doing that `ionic capacitor sync --prod` is _not_ doing. But it sort of makes sense why this wasn't noticed before.

**Comment by pkalita-lbl** [comment]
I think I understand what's going on now.

* The app picks up the version number from `import.meta.env.PACKAGE_VERSION`
* The `PACKAGE_VERSION` key is injected into `import.meta.env` by [vite-plugin-package-version](https://github.com/smnhgn/vite-plugin-package-version)
* Taking a [little peek under the hood](https://github.com/smnhgn/vite-plugin-package-version/blob/1674a8782dfa4cc3adf508736eff82b7a1e9234f/packages/plugin/src/index.ts#L11) I see that that plugin gets the package version from the `npm_package_version` environment variable.
* That [environment variable](https://docs.npmjs.com/cli/v7/using-npm/scripts#packagejson-vars) is only available when running NPM scripts!

Putting that all togethe: because our build and deploy instructions say to run `ionic capacitor sync --prod` _directly_ (not via a script), the version number won't be there. Whereas running `npm run sim.ios` (a script!) will have access to the underlying environment variable. 

So the simplest thing to do here would be to add a new script to our `package.json` file (called, like, I don't know? `build.capacitor` or something?) that runs `ionic capacitor sync --prod`. Then our release instructions should be updated to use the new script instead of calling the `ionic` CLI directly.

**Comment by pkalita-lbl** [comment]
It also makes me wonder if we get much out of that Vite plugin or whether it's just obfuscating issues like this. Would it be clearer if our `config.ts` module directly used `process.env.npm_package_version`?

**Comment by pkalita-lbl** [comment]
Stealing this issue from @eecavanna since I'm already touching some of this stuff.

**Comment by ssarrafan** [comment]
Appears to be active. I will move to the next sprint unless @pkalita-lbl you're planning to finish this today?

**Comment by pkalita-lbl** [comment]
Actively working on this. Will be finished next week.
