### ISSUE TITLE
Already existing study

### ISSUE THREAD

**Issue by cpavloud** [microbiomedata/nmdc-field-notes#169]
### Bug details

I logged in for the first time (using ORCID), but there is an already existing study in my account (Name: aaa ddvddd) containing 0 samples. 

### Steps to reproduce

1. Download and install [org.microbiomedata.fieldnotes-v0.1.0-build.4.apk](https://github.com/microbiomedata/nmdc-field-notes/releases/download/v0.1.0/org.microbiomedata.fieldnotes-v0.1.0-build.4.apk)
2. Launch app
3. Log in using ORCID
4. Tap "Studies"

### Device type

Android

### Operating system version

13

**Comment by pkalita-lbl** [comment]
Thank you for the bug report!

Our records indicate that study was created through the [NMDC Submission Portal](https://data.microbiomedata.org/submission/home) on 2024-07-25. Since the app and the submission portal are sync'd with each other, it is expected that you would see that study in the app. 

If that study was created in error or as a test, you can delete it via the app by:

1. From the Studies tab tap the study name
2. In the header tap Edit
3. In the header tap the three dot icon
4. In the resulting menu tap Delete Study

Once deleted, the study will not appear in the app or submission portal.

**Comment by cpavloud** [comment]
Ok. So you are saying that I probably created the study myself (but I eventually forgot about it). 
It could be this way. 
I didn't remember creating the study through the portal and so I thought it was a bug of the system, something that is there for every user without being created by the users. 
I will delete it and proceed!

**Comment by eecavanna** [comment]
Thanks for reporting this, @cpavloud!

Knowing that this was something that you found confusing was helpful to those of us working on an "in-app tours" feature, which was included in a new beta build of the app that we published this afternoon. In the tour of the "Studies" screen (when logged in), we included a statement saying that the screen lists studies that were created _either_ through the app or the NMDC Submission Portal.

You can download that new beta build [here](https://github.com/microbiomedata/nmdc-field-notes/releases/download/v0.1.0/org.microbiomedata.fieldnotes-v0.1.0-build.5.apk) (or go to the [Release v0.1.0](https://github.com/microbiomedata/nmdc-field-notes/releases/tag/v0.1.0) page, scroll down to the "Assets" section, and tap on `org.microbiomedata.fieldnotes-v0.1.0-build.5.apk`).

Thanks again for taking the time to leave us that feedback (and reporting bug [#170](https://github.com/microbiomedata/nmdc-field-notes/issues/170), which is also fixed in that new build).
