### ISSUE TITLE
2nd test - comments on app

### ISSUE THREAD

**Issue by patrickchain** [microbiomedata/nmdc-field-notes#184]
### Bug summary

just a list of comments

### Bug details

General questions for study creation:
it looks like we must select an environmental template - what of studies that require more than one sample type...like studies that happen at an interface - say water and soil, or soil and host-associated...can this be moved to the level of each sample, or can you select multiple (and be allowed to edit?)

name and ORCID can auto-populate - can you do the same with email (even if over-ridden by user).  Perhaps if not, can you check the studies within the app with the same ORCID/user and autopopulate email....in case they mistype their email?

-----

sample creation - (soil template study)
Can you NOT make analysis/data type required? some simply collect for future use. Also some can collect for multiple uses, can you make this multiple choice? and perhaps add free text as well in case they want to use for something else?
Should this not be linked instead to actual data generated instead, and have that data file point back to this sample?

is there  any control or lookup to make sure that entries can be correct - i entered false info into broad-scale environmental context, and in local environmental context...
oddly, i entered in the example given in environmental medium but it says it's invalid!

Can you default to auto-fill when only one entry is possible - like in Ecosystem - the only thing possible is 'environmental' - and then same with subclasses of ecosystem....

i like the use GPS feature - but when i entered geographic location by name, i again entred the exact example listed but it says invalid.

why does depth in meters not accept 0? hmmm...also doesn't accept 1, which is another example provided. but 0-1 works.

### Anything else?

app auto-updated, that's nice.

i seem to have lost my prior study/samples...oh well.

### Device type

Apple

**Comment by pkalita-lbl** [comment]
Thanks for the feedback! Let me try to tease apart some of this and see what might be actionable.

> it looks like we must select an environmental template - what of studies that require more than one sample type...like studies that happen at an interface - say water and soil, or soil and host-associated...can this be moved to the level of each sample, or can you select multiple (and be allowed to edit?)

This is a limitation imposed by the portal backend at the moment. However, that will be changing shortly. The following issues track changes to the portal and the app, respectively, which will allow a study to be associated with multiple environmental templates:

* https://github.com/microbiomedata/nmdc-server/issues/1367
* https://github.com/microbiomedata/nmdc-field-notes/issues/177

Once the changes for those two issues are deployed you will be able to select, say, both water and soil for a single study. In that case when you attach a new sample to that study the app will ask you whether you'd like to use the water or soil template for that sample.

> name and ORCID can auto-populate - can you do the same with email (even if over-ridden by user). Perhaps if not, can you check the studies within the app with the same ORCID/user and autopopulate email....in case they mistype their email?

The portal backend does not collect user email addresses at the moment. All we know about the logged-in user is their name and ORCID iD. There is planned work to address that on the portal side:

* https://github.com/microbiomedata/issues/issues/767

My opinion is we should wait for the portal backend to sort that out and then utilize what the backend provides in the app.

> Can you NOT make analysis/data type required? some simply collect for future use. Also some can collect for multiple uses, can you make this multiple choice? and perhaps add free text as well in case they want to use for something else?
Should this not be linked instead to actual data generated instead, and have that data file point back to this sample?

This is one of those instances where NMDC being relentlessly schema-driven comes back to bite us a bit. The sample metadata entry screens are entirely driven by the [submission schema](https://github.com/microbiomedata/submission-schema). The submission schema marks slots (like `analysis/data type`) as required if we require them _before finalizing a submission_ (i.e. before saying "here you go NMDC, I'm done with this, you look at it now"). However, as you're getting at, the app is mainly about collecting what you can in the field, assuming that you'll fill out the rest and _finalize_ later via the portal. 

Probably what we need to do is to annotate the schema in some way where we can explicitly mark slots (like, say, `depth`) as "you should almost certainly collect this in the field" as opposed to just dual-purposing the slot's required attribute.

The `analysis/data type` slot is already multivalued, so you should be able to select multiple options:

<img width="423" alt="image" src="https://github.com/user-attachments/assets/6d23204b-918a-4e0b-81d3-21822f30c9c0">

If you aren't seeing that behavior please let me know. As far as the other changes to that slot like allowing free-text entries or deriving it from generated data, that's a much bigger schema and workflow question that feels outside of the scope of the app to me.

> is there any control or lookup to make sure that entries can be correct - i entered false info into broad-scale environmental context, and in local environmental context...

The three ENVO slots (`broad-scale environmental context`, `local environmental context`, and `environmental medium`) _should_ (in theory) be offering you options to select from instead of asking you to type something in. This is a known bug:

* https://github.com/microbiomedata/nmdc-field-notes/issues/176

> oddly, i entered in the example given in environmental medium but it says it's invalid!

> i like the use GPS feature - but when i entered geographic location by name, i again entred the exact example listed but it says invalid.

> why does depth in meters not accept 0? hmmm...also doesn't accept 1, which is another example provided. but 0-1 works.

`depth` for soil and sediment samples requires a range (i.e. not just `0`). Why? That's the way some soil scientist said it should be :grin: (https://github.com/microbiomedata/submission-schema/issues/95)

However the examples for all slots should definitely be valid. The examples come from the schema itself, so I created an issue in the submission schema repository to address this:

* https://github.com/microbiomedata/submission-schema/issues/227

> i seem to have lost my prior study/samples...oh well.

That is definitely not expected. If you can reproduce that issue I'd be happy to investigate that.

**Comment by patrickchain** [comment]
hey Patrick - thanks! good explanations for most...

for the analysis/data type - i meant can you allow multiple selections - like i'd like to generate both proteomic and genomic data from this sample......

i ?think? it only allows a choice of 1 from multiple (limited) options....so the query about offering up free text is geared more toward folks who want to generate other types of microbiome data that we have not yet accommodated in the schema....how to deal with this downstream, i'm not sure yet....hadn't thought that far.

the studies i lost i created when the app was first available - Eric helped me to get it, and i tried it out but can't find what i made...that was before the broader release to internal testers though, so didn't know if that's unexpected or not. thought i'd mention it.


________________________________
From: Patrick Kalita ***@***.***>
Sent: Tuesday, September 24, 2024 12:10 PM
To: microbiomedata/nmdc-field-notes ***@***.***>
Cc: Chain, Patrick Sam Guy ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/nmdc-field-notes] 2nd test - comments on app (Issue #184)


Thanks for the feedback! Let me try to tease apart some of this and see what might be actionable.

it looks like we must select an environmental template - what of studies that require more than one sample type...like studies that happen at an interface - say water and soil, or soil and host-associated...can this be moved to the level of each sample, or can you select multiple (and be allowed to edit?)

This is a limitation imposed by the portal backend at the moment. However, that will be changing shortly. The following issues track changes to the portal and the app, respectively, which will allow a study to be associated with multiple environmental templates:

  *   microbiomedata/nmdc-server#1367<https://urldefense.com/v3/__https://github.com/microbiomedata/nmdc-server/issues/1367__;!!Bt8fGhp8LhKGRg!EHxH_kT01erkDNeuQxR3Gvt7ZqdA__rUD2Lp7hrAi1ko2WcFdfhcVNTodfMTjV4MEEgg1lL5Q7EU2UVT6uzYzRc$>
  *   #177<https://urldefense.com/v3/__https://github.com/microbiomedata/nmdc-field-notes/issues/177__;!!Bt8fGhp8LhKGRg!EHxH_kT01erkDNeuQxR3Gvt7ZqdA__rUD2Lp7hrAi1ko2WcFdfhcVNTodfMTjV4MEEgg1lL5Q7EU2UVTw3pOMUI$>

Once the changes for those two issues are deployed you will be able to select, say, both water and soil for a single study. In that case when you attach a new sample to that study the app will ask you whether you'd like to use the water or soil template for that sample.

name and ORCID can auto-populate - can you do the same with email (even if over-ridden by user). Perhaps if not, can you check the studies within the app with the same ORCID/user and autopopulate email....in case they mistype their email?

The portal backend does not collect user email addresses at the moment. All we know about the logged-in user is their name and ORCID iD. There is planned work to address that on the portal side:

  *   microbiomedata/issues#767<https://urldefense.com/v3/__https://github.com/microbiomedata/issues/issues/767__;!!Bt8fGhp8LhKGRg!EHxH_kT01erkDNeuQxR3Gvt7ZqdA__rUD2Lp7hrAi1ko2WcFdfhcVNTodfMTjV4MEEgg1lL5Q7EU2UVTGCMpbvQ$>

My opinion is we should wait for the portal backend to sort that out and then utilize what the backend provides in the app.

Can you NOT make analysis/data type required? some simply collect for future use. Also some can collect for multiple uses, can you make this multiple choice? and perhaps add free text as well in case they want to use for something else?
Should this not be linked instead to actual data generated instead, and have that data file point back to this sample?

This is one of those instances where NMDC being relentlessly schema-driven comes back to bite us a bit. The sample metadata entry screens are entirely driven by the submission schema<https://urldefense.com/v3/__https://github.com/microbiomedata/submission-schema__;!!Bt8fGhp8LhKGRg!EHxH_kT01erkDNeuQxR3Gvt7ZqdA__rUD2Lp7hrAi1ko2WcFdfhcVNTodfMTjV4MEEgg1lL5Q7EU2UVTOsQpFPY$>. The submission schema marks slots (like analysis/data type) as required if we require them before finalizing a submission (i.e. before saying "here you go NMDC, I'm done with this, you look at it now"). However, as you're getting at, the app is mainly about collecting what you can in the field, assuming that you'll fill out the rest and finalize later via the portal.

Probably what we need to do is to annotate the schema in some way where we can explicitly mark slots (like, say, depth) as "you should almost certainly collect this in the field" as opposed to just dual-purposing the slot's required attribute.

The analysis/data type slot is already multivalued, so you should be able to select multiple options:

image.png (view on web)<https://urldefense.com/v3/__https://github.com/user-attachments/assets/6d23204b-918a-4e0b-81d3-21822f30c9c0__;!!Bt8fGhp8LhKGRg!EHxH_kT01erkDNeuQxR3Gvt7ZqdA__rUD2Lp7hrAi1ko2WcFdfhcVNTodfMTjV4MEEgg1lL5Q7EU2UVTSUoacFA$>

If you aren't seeing that behavior please let me know. As far as the other changes to that slot like allowing free-text entries or deriving it from generated data, that's a much bigger schema and workflow question that feels outside of the scope of the app to me.

is there any control or lookup to make sure that entries can be correct - i entered false info into broad-scale environmental context, and in local environmental context...

The three ENVO slots (broad-scale environmental context, local environmental context, and environmental medium) should (in theory) be offering you options to select from instead of asking you to type something in. This is a known bug:

  *   #176<https://urldefense.com/v3/__https://github.com/microbiomedata/nmdc-field-notes/issues/176__;!!Bt8fGhp8LhKGRg!EHxH_kT01erkDNeuQxR3Gvt7ZqdA__rUD2Lp7hrAi1ko2WcFdfhcVNTodfMTjV4MEEgg1lL5Q7EU2UVTZaGfKHQ$>

oddly, i entered in the example given in environmental medium but it says it's invalid!

i like the use GPS feature - but when i entered geographic location by name, i again entred the exact example listed but it says invalid.

why does depth in meters not accept 0? hmmm...also doesn't accept 1, which is another example provided. but 0-1 works.

depth for soil and sediment samples requires a range (i.e. not just 0). Why? That's the way some soil scientist said it should be 😁 (microbiomedata/submission-schema#95<https://urldefense.com/v3/__https://github.com/microbiomedata/submission-schema/issues/95__;!!Bt8fGhp8LhKGRg!EHxH_kT01erkDNeuQxR3Gvt7ZqdA__rUD2Lp7hrAi1ko2WcFdfhcVNTodfMTjV4MEEgg1lL5Q7EU2UVTC09Y4o8$>)

However the examples for all slots should definitely be valid. The examples come from the schema itself, so I created an issue in the submission schema repository to address this:

  *   microbiomedata/submission-schema#227<https://urldefense.com/v3/__https://github.com/microbiomedata/submission-schema/issues/227__;!!Bt8fGhp8LhKGRg!EHxH_kT01erkDNeuQxR3Gvt7ZqdA__rUD2Lp7hrAi1ko2WcFdfhcVNTodfMTjV4MEEgg1lL5Q7EU2UVTjZ19stY$>

i seem to have lost my prior study/samples...oh well.

That is definitely not expected. If you can reproduce that issue I'd be happy to investigate that.
