### ISSUE TITLE
Add list of studies to home screen

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#29]
Once a user is logged in, the home screen should display:

* Studies listed by name
* For each study an expandable list of samples by name
* A button/link to navigate to a page for creating a new study (the destination page doesn't need to be implemented with this issue)

Relevant part of the [mockups](https://design.penpot.app/#/workspace/c29b5282-da70-8012-8003-6e07eabfa764/aba078d3-8498-80bd-8003-70a9899d77ec?page-id=aba078d3-8498-80bd-8003-70a9899d77ed):
![Untitled](https://github.com/microbiomedata/nmdc-field-notes/assets/102547565/7ea31531-e0af-4ed3-b530-df248fc9f685)

Some things that may need discussion or clarification:
* I don't know if the "Sync with NMDC Submission Portal" button is necessary. I think that can happen automatically in the background.
* My recollection was that unstructured notes ("Quick Note" in the mockup) would be attached to specific studies. I'm not sure what the advantage of them being detached from a study would be -- it also has significant backend data storage implications to have them not attached to a study. 

Potentially useful Ionic component:
* https://ionicframework.com/docs/api/accordion

**Comment by simroux** [comment]
My two cents:
- I agree on the "Sync with NMDC Sub portal", but if we don't have a button then we should have an icon that indicates whether a sample/study is synced vs out of sync ? 
- Agreed on the "Quick Note", would make more sense to have it within each study. Otherwise I feel people can use any App they like to take Notes on their phone, especially if we don't display these ?

**Comment by eecavanna** [comment]
Side note: During today's squad meeting, an attendee suggested that the screen say "My studies" as opposed to "Your studies".
